// <auto-generated />
using System;
using CopilotPluginApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CopilotPluginApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("CopilotPluginApi.Data.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CacheHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_hit");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completion_tokens");

                    b.Property<decimal>("CostEstimateUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_estimate_usd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Degraded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("degraded");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_used");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("requestId");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("sessionId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
