namespace CopilotPluginApi.Models;

/// <summary>
/// Represents the outcome of an LLM completion request, including token usage and cost metadata.
/// </summary>
/// <param name="Content">The text content returned by the model.</param>
/// <param name="ModelUsed">The deployment or model identifier that produced the response.</param>
/// <param name="PromptTokens">The number of prompt tokens consumed by the request.</param>
/// <param name="CompletionTokens">The number of completion tokens generated by the model.</param>
/// <param name="Degraded">A value indicating whether fallback or degraded behavior was used.</param>
/// <param name="CostEstimateUsd">The estimated USD cost of the request.</param>
public sealed record LlmResult(
    string Content,
    string ModelUsed,
    int PromptTokens,
    int CompletionTokens,
    bool Degraded,
    double CostEstimateUsd);
